# My theme
theme: jekyll-theme-architect

# Use Github Flavoured Markdown
markdown: GFM

# Specific for BayesicFitting
title: [BayesicFitting]
description: [Bayesian Fitting and Evidence Calculation]
examples: 
  - img: ./docs/images/rijntemp.png
    cap: "Average temperature of the Rhine"
  - img: ./docs/images/Julius.png
    cap: "Light absorption by tea"
  - img: ./docs/images/HD76700.png
    cap: "Exoplanet around HD76700"
  - img: ./docs/images/83Aqr.png
    cap: "Orbit of doublestar 83 Aqr"
  - img: ./docs/images/Gregory.png
    cap: "A signal or not"

